---
# Install nginx
 - name: Make build dir
   command: mkdir -p {{ build_dir }}
   sudo: yes

 - name: Copy the gpg keyring to verify sources (required for buildstaticnginx module).
   copy: src=keyring.gpg dest={{ build_dir }}/nginx-compile-keyring.gpg
   sudo: yes

 - name: Create upstart script
   template: src=upstart-conf dest=/etc/init/nginx.conf
   sudo: yes

 - name: Build static nginx
   buildstaticnginx: nginx_version={{ nginx_version }} openssl_version={{ openssl_version }} pcre_version={{ pcre_version }} install_prefix={{ install_prefix }}
   sudo: yes
   notify: restart nginx
